services:
  server:
    container_name: "snippet-manager"
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8081:8081
    depends_on:
      - postgres

  postgres:
    container_name: "snippet-manager-db"
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
    volumes:
      - snippet_manager_data:/var/lib/postgresql/data

  api:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_APP_NAME: "asset-service"
      NEW_RELIC_AGENT_ENABLED: "false"


  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace

  redis:
    container_name: "snippets-redis"
    image: redis:6-alpine
    ports:
        - "6379:6379"

volumes:
  snippet_manager_data:
  blob:
    external: false
